config/routes.rb
Rails.application.routes.draw do
  get "home/projects"
  get "home/contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<div class="row">
  <h1>Contacto</h1>
</div>
<div class="container text-start">
  <form>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Dirección de Correo</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Contraseña</label>
      <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Recordar</label>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</div>

app/views/home/index.html.erb
<div class="row">
  <h1>Bienvenido a este Portafolio</h1>
</div>
<div class="row">
  <p>Aqui podras encontrar algunos proyectos desarrollados en Ruby y otros aplicando MVC con Rails!</p>
  <figure>
    <%= image_tag "ROR_Logo.png", alt: "Logo_Rails" %>
  </figure>
</div>
<div class="container text-center mt-4">
  <div class="row">
    <div class="col-6">
      <div class="card" ">
        <div class="card-header">
          Proyectos
        </div>
        <%= link_to(home_projects_path) do %>
          <%= image_tag("Proyectos.png", alt: "Proyectos", class:"img_resize") %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="card" ">
        <div class="card-header">
          Contacto
        </div>
        <%= link_to(home_contact_path) do %>
          <%= image_tag("Contacto.png", alt: "Contacto", class:"img_resize") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/projects.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col pb-2">
      <div class="card mx-auto d-block py-3" style="width: 18rem;">
        <%= image_tag("proyectos/PiedraTijeraPapel.png", alt: "Proyecto Piedra-Papel-Tijera", class:"mx-auto d-block img_resize_proyectos") %>
        <div class="card-body">
          <h5 class="card-title">Proyecto Piedra-Papel-Tijera</h5>
          <p class="card-text">Popular juego creado en base a ruby para ejecutar desde consola con un argumento inicial</p>
          <%= button_to "Ir al Proyecto", "https://github.com/JuanGonzalezJara/PiedraPapelTijera", target: "_blank", class:"btn btn-secondary rounded_button", method: :get%>
        </div>
      </div>
    </div>
    <div class="col pb-2">
      <div class="card mx-auto d-block py-3" style="width: 18rem;">
        <%= image_tag("proyectos/TripleProyecto.png", alt: "Proyecto Triple", class:"mx-auto d-block img_resize_proyectos") %>
        <div class="card-body">
          <h5 class="card-title">Proyecto Triple</h5>
          <p class="card-text">Desafio orientado al uso de Metodos para la resolucion de requerimientos</p>
          <%= button_to "Ir al Proyecto", "https://github.com/JuanGonzalezJara/Desafio_RoR_Unidad4_M3_3", target: "_blank", class:"btn btn-secondary rounded_button", method: :get%>
        </div>
      </div>
    </div>
    <div class="col pb-2">
      <div class="card mx-auto d-block py-3" style="width: 18rem;">
        <%= image_tag("proyectos/Ciclos.png", alt: "Proyecto Ciclos", class:"mx-auto d-block img_resize_proyectos") %>
        <div class="card-body">
          <h5 class="card-title">Proyecto Ciclos en Ruby</h5>
          <p class="card-text">Desafio orientado al uso de Cliclos While o For para la resolucion de requerimientos.</p>
          <%= button_to "Ir al Proyecto", "https://github.com/JuanGonzalezJara/Desafio_RoR_Unidad4_M3_2", target: "_blank", class:"btn btn-secondary rounded_button", method: :get%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio_RoR_Unidad5_M1_1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# CDN de Bootstrap - CSS %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "style" %>
  </head>
  <body>
    <%# NavBar %>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to(home_contact_path) do %>
          <%= image_tag("ruby-icon.png", alt: "icono") %>
        <% end %>
        <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ps-3" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Home", root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Projectos", home_projects_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contacto", home_contact_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%# Content %>
    <div class="container text-center pt-2">
      <%= yield %>
    </div>
    <footer class="pt-5">
      <div class="card mx-3 mt-5">
        <div class="card-body">
          <p class="card-text text-center">Copyright © 2023 - Todos los derechos y los izquierdos reservados</p>
        </div>
      </div>
    </footer>
    <%# CDN de Bootstrap - JS %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>